### PR TITLE
Made the Error struct Send + Sync

### LINKED ISSUE #442: tera::Error cannot be sent between threads safely
Hi, i'm using error_chain in a program that does tera templating in a rayon loop. Updating from v0.11 to v1.0.0-beta14 produced the following error:

```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
  --> src/main.rs:21:1
   |
21 | / error_chain!{
22 | |     foreign_links {
23 | |         Http(reqwest::Error);
24 | |         Json(serde_json::Error);
...  |
27 | |     }
28 | | }
   | |_^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn std::error::Error + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + 'static)>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + 'static)>>`
   = note: required because it appears within the type `tera::errors::Error`
   = note: required because it appears within the type `ErrorKind`
   = note: required because it appears within the type `Error`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

Full extract from my source file:
```
error_chain!{
    foreign_links {
        Http(reqwest::Error);
        Json(serde_json::Error);
        Io(std::io::Error);
        Templating(tera::Error);
    }
}
```

### PR DESCRIPTION
**Pull request by AxelMontini**
In order to be able to construct `anyhow::Error`s from `tera::Error`s, we must make this crate errors `Send + Sync`.

To do so it's only necessary to change 3 lines of code, but I'm not sure whether this is going to be a breaking change or not.

IMO this is a small but great addition that contributes to the usability of this crate.

Edit:
Fixes #442

### CODE REVIEW

**Comment by Keats** [comment]
Thanks, can you add a test like https://stackoverflow.com/questions/41599921/how-to-define-a-struct-that-is-sendsync-and-is-holding-a-iowrite-member?rq=1 to ensure it's correct?

**Comment by AxelMontini** [comment]
Now the problem is that the CI fails because a command containing `&&` is being run on windows. Gonna create a PR for that too.

File: tests/render_fails.rs [hunk 1]
```diff
@@ -142,3 +142,18 @@ fn test_error_in_macro_location() {
         "Failed to render 'error-location/error_in_macro.html': error while rendering macro `macros::cause_error`"
     );
 }
+
+#[test]
+fn test_error_is_send_and_sync() {
```
Comment (Keats) [inline tests/render_fails.rs]: sorry, can you move it to a new test module in src/errors.rs so it's co-located?

**Comment by Keats** [comment]
For the Windows failure I'm confused, it passes on https://github.com/Keats/tera/pull/353/checks?check_run_id=267363501

**Comment by AxelMontini** [comment]
> For the Windows failure I'm confused, it passes on https://github.com/Keats/tera/pull/353/checks?check_run_id=267363501

Probably Beta stuff. I'm not even sure where to check for changes in GitHub Actions, but probably something has been changed in the last ~8 days.

PR to fix that too: #459

File: src/errors.rs [hunk 2]
```diff
@@ -160,3 +160,21 @@ impl From<serde_json::Error> for Error {
 }
 /// Convenient wrapper around std::Result.
 pub type Result<T> = ::std::result::Result<T, Error>;
+
+#[cfg(test)]
+mod tests {
+    #[test]
+    fn test_error_is_send_and_sync() {
```
Comment (CAD97) [inline src/errors.rs]: Typically this is done with `fn test_send_sync<T: Send + Sync>() test_send_sync::<Error>()`. Note that `fn very_useless_function` isn't actually needed here; the `impl SendSync for Error` will fail if the supertraits aren't supplied.

There's no way to make it fail at runtime rather than compile time though, unless doing a stupidly complex "faux specialization" trick which really isn't worth it; SendSync is a test you want to stop you immediately if you break it anyway.

Comment (AxelMontini) [reply src/errors.rs]: *Improved*

**Comment by Keats** [comment]
Thanks!
